/**
 * generate-env.cjs
 *
 * Reads .env and bakes runtime secrets directly into electron/_env_generated.ts
 * so they get compiled into the ASAR bundle instead of shipped as a readable
 * plain-text file in the resources folder.
 *
 * GH_TOKEN is intentionally excluded — it is only needed at publish time,
 * not at app runtime.
 *
 * Run automatically as part of "npm run build".
 * The generated file is in .gitignore and must never be committed.
 */

const fs = require('fs')
const path = require('path')

const ROOT = path.join(__dirname, '..')
const ENV_FILE = path.join(ROOT, '.env')
const OUT_FILE = path.join(ROOT, 'electron', '_env_generated.ts')

// Variables we want to bake into the runtime bundle
const RUNTIME_VARS = ['ANTHROPIC_API_KEY', 'OPENAI_API_KEY', 'DEEPGRAM_API_KEY', 'SUPABASE_URL', 'SUPABASE_ANON_KEY', 'GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET']

// Parse .env file
function parseEnv(filePath) {
  if (!fs.existsSync(filePath)) {
    console.warn('[generate-env] .env not found — using process.env only')
    return {}
  }
  const lines = fs.readFileSync(filePath, 'utf-8').split('\n')
  const result = {}
  for (const line of lines) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const eq = trimmed.indexOf('=')
    if (eq === -1) continue
    const key = trimmed.slice(0, eq).trim()
    const val = trimmed.slice(eq + 1).trim().replace(/^["']|["']$/g, '')
    result[key] = val
  }
  return result
}

const envVars = parseEnv(ENV_FILE)

// Build the generated file content
const entries = RUNTIME_VARS.map((key) => {
  // Prefer actual environment variable (CI/CD), fall back to .env file
  const value = process.env[key] ?? envVars[key] ?? ''
  if (!value) {
    console.warn(`[generate-env] WARNING: ${key} is not set`)
  }
  const escaped = value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
  return `  ${key}: '${escaped}'`
})

const output = `// AUTO-GENERATED by scripts/generate-env.cjs — DO NOT EDIT, DO NOT COMMIT
// This file contains runtime secrets baked in at build time.
export const ENV: Record<string, string> = {
${entries.join(',\n')}
}
`

fs.writeFileSync(OUT_FILE, output, 'utf-8')
console.log('[generate-env] ✅ electron/_env_generated.ts written')
